version: '3.3'
services:
  nginx:
    image: nginx:1.9
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./provision/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    links:
      - php

  php:
    build: .
    container_name: php-fpm

  frontend:
   image: bpastukh/tracking-app-fe:1.0.0
   container_name: frontend
   ports:
     - "4000:80"

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
