version: '3.3'
services:
  nginx:
    image: nginx:1.9
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./:/app
    links:
      - php

  php:
    build: .
    container_name: php-fpm

  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: test
